### ISSUE TITLE
Crash on app start after updating from r6.5-d

### ISSUE THREAD

**Issue by MPeti1** [Magisk-Modules-Repo/Dolby-Atmos-LeEco-Le-Pro-3#2]
Crash log:
`java.lang.RuntimeException: Exception: can not load settings.
 at com.atmos.api.DsBase.convertErrorCodeToException(DsBase.java:114)
 at com.atmos.api.DsFocus.getProfile(DsFocus.java:497)
 at com.atmos.daxappUI.MainActivity.onClientConnected(MainActivity.java:1294)
 at com.atmos.api.DsBase$1.onServiceConnected(DsBase.java:371)
 at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1233)
 at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1250)
 at android.os.Handler.handleCallback(Handler.java:742)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:5529)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)`

**Comment by MPeti1** [comment]
SOLVED: when i first updated Viper, for some reason Dolby and JamesDSP went gone from the installed list and i remembered bad what version i used. This version become uncompatbile/buggy with my phone when i updated my dsp-s at Jan 19.
